Back_end/.gitignore
Back_end/index.js
Back_end/package-lock.json
Back_end/package.json
Back_end/src/app.js
Back_end/src/db.js
Back_end/src/routes/index.js

Se inicializa back, ya se puede levantar server

Inicializando Back

---

Back_end/src/models/Order.js
Back_end/src/models/Products.js
Back_end/src/models/User.js

Models creado: Users,Product, Order.

Kevin backend models

---

Front_end/package-lock.json
Front_end/src/App.jsx
Front_end/src/Components/Detail/Detail.jsx
Front_end/src/Components/index.js
Front_end/src/main.jsx
Front_end/src/pages/Aboutpage/Aboutpage.jsx
Front_end/src/pages/Detailpage/Detailpage.jsx
Front_end/src/pages/Homepage/Homepage.jsx
Front_end/src/pages/Landingpage/Landingpage.jsx
Front_end/src/pages/index.js
Front_end/src/redux/reducer/reducer.js
Front_end/src/redux/store/store.js

Cree las rutas y paginas básicas para empezar a trabajar con los componentes y estilos

Create pages and routes

---

Back_end/src/controllers/productsControllers.js

Creamos controllers y asignamos la funcionalidad correspondiente.

Creando Controllers y dando funcionalidad

---

Back_end/src/controllers/productsControllers.js
Back_end/src/controllers/usersControllers.js
Back_end/src/handlers/productsHandlers.js
Back_end/src/handlers/usersHandlers.js

Agregue controlers para los usuarios y anadi un nuevo controller a products

usersControllers y productsControllers

---

Front_end/src/App.jsx
Front_end/src/Components/Card/card.jsx
Front_end/src/Components/Card/card.module.css

se solicito la información al Json para modularizar cards, falta redux

carcodeo de informacion de la api para renderizar cadr

---

Front_end/src/redux/actions/actions.js

URL en actions

---

Back_end/src/controllers/productsControllers.js
Back_end/src/controllers/usersControllers.js
Back_end/src/handlers/productsHandlers.js
Back_end/src/handlers/usersHandlers.js
Back_end/src/routes/productsRouter.js
Back_end/src/routes/usersRouter.js

Cree el delete apra ambos models (products y users)

creando metodos delete para products/users y post para products

---

Front_end/src/Components/SearchBar/SearchBar.jsx
Front_end/src/Components/SearchBar/SearchBar.module.css
Front_end/src/redux/actions/actions.js
Front_end/src/redux/reducer/reducer.js

Hay que aceptar los cambios realizados en el archivo actions.

Estados globales

---

Front_end/src/Components/Landing/Landing.jsx
Front_end/src/Components/SearchBar/SearchBar.jsx
Front_end/src/Components/SearchBar/SearchBar.module.css
Front_end/src/redux/actions/actions.js
Front_end/src/redux/reducer/reducer.js

SearchBar Lista. Cambie la URL por la que mandaron desde el back

SearchBar y getAlProducts Listos

---

Back_end/src/models/Product.js

Resolviendo conflito model

---

Back_end/src/models/Product.js

Fix Models Validations

---

Back_end/src/api/products.json
Back_end/src/controllers/categoryControllers.js
Back_end/src/controllers/orderControllers.js
Back_end/src/controllers/productsControllers.js
Back_end/src/controllers/usersControllers.js
Back_end/src/db.js
Back_end/src/handlers/orderHandler.js
Back_end/src/handlers/productsHandlers.js
Back_end/src/models/Category.js
Back_end/src/models/Order.js
Back_end/src/models/Product.js
Back_end/src/routes/index.js
Back_end/src/routes/orderRoute.js
Back_end/src/routes/productsRouter.js
Back_end/src/routes/usersRouter.js

Se cambio Id, se hizo relación entre Category/product con base de datos y se creo ruta Order.

Relaciones entre tablas

---

Back_end/src/controllers/productsControllers.js

Se corrigió relación Product/category, agregándole el name de la categoría se crea el producto correctamente.

Post Product/Relacion Category OK

---

Back_end/src/handlers/productsHandlers.js
Front_end/src/Components/index.js

Había una importación errónea en el componente cardprofile y se rompía el front. 
Oculte a su vez las credenciales enviadas vía post product del navegador.

arreglando mala importacion de carprofile / ocultando credenciales post

---

Back_end/src/app.js
Back_end/src/controllers/categoryControllers.js
Back_end/src/controllers/productsControllers.js
Back_end/src/handlers/categoryHandlers.js
Back_end/src/handlers/productsHandlers.js
Back_end/src/utils/filter.js
Back_end/src/utils/pagination.js

Se implemento el cambio en el paginado y filtros desde el back(A-Z/Z-A/precio Asc/Desc.

Implementacion de paginado y filtros desde el back

---

Back_end/src/controllers/categoryControllers.js
Back_end/src/controllers/productsControllers.js
Back_end/src/handlers/productsHandlers.js
Back_end/src/models/Product.js
Back_end/src/utils/filter.js

Filtro gender/ category desde back la combinación de filtro se hace bien.     http://localhost:3001/products?gender=masculino&category=pantalones&sortBy=price&sortOrder=asc

Filtro gender/ category desde back

---

Back_end/src/controllers/usersControllers.js
Back_end/src/db.js
Back_end/src/handlers/usersHandlers.js
Back_end/src/routes/usersRouter.js

se agrego la ruta tipo PUT /users/:idUser para asi editar los datos del usuario

ruta editar datos usuario

---

Back_end/src/controllers/productsControllers.js
Back_end/src/handlers/productsHandlers.js
Front_end/src/Components/SearchBar/SearchBar.jsx
Front_end/src/redux/actions/actions.js
Front_end/src/redux/reducer/reducer.js

Se soluciono problemas en searchbar, se modifico back y front.

Se soluciono problemas en searchbar

---

Front_end/src/Components/Create_form/Create_form.jsx
Front_end/src/Components/Create_form/Create_form.module.css

Se corrigió error en tipio y botón delate de img.

Se corrigio form error de tipeo

---

Front_end/src/Components/Create_form/Create_form.jsx
Front_end/src/Components/Menu/Menu.jsx
Front_end/src/Components/Menu/menu.module.css
Front_end/src/redux/actions/actions.js

Se corrigió idioma en filtros/Form y funcionalidad.

Se corrigio idioma en filtros/Form y funcionalidad

---

Back_end/src/controllers/orderControllers.js
Back_end/src/models/OrderDetail.js
Front_end/src/Components/Cart/Cart.jsx
Front_end/src/redux/actions/actions.js

Se agrego detalle ede name y price en la orden de compra

Se agrego detalle ede name y price en la orden de compra

---

Back_end/src/controllers/orderControllers.js
Back_end/src/controllers/productsControllers.js
Back_end/src/handlers/productsHandlers.js
Back_end/src/models/Order.js
Back_end/src/models/Product.js

Se le agrego la propiedad size al back falta renderizar en frontend.

Se le agrego la propiedad size al back

---

Back_end/config.js
Back_end/src/utils/emailers.js

Solucion emails variables config/env

Solucion emails

---

Front_end/src/Components/Create_form/Create_form.jsx

Se corrigio size en Create

---

Back_end/src/controllers/orderControllers.js
Back_end/src/models/Order.js
Back_end/src/routes/productsRouter.js
Front_end/src/Components/Cart/Cart.jsx

Se incorporo email y name a la order!

 Se incorporo email y name a la order!

---

Front_end/src/Components/Register/Register.jsx
Front_end/src/pages/Loginpage/Loginpage.jsx
Front_end/src/redux/actions/actions.js

Correcciones

---

Back_end/src/controllers/orderControllers.js
Back_end/src/controllers/payment.Controller.js
Back_end/src/controllers/productsControllers.js
Front_end/src/Components/Create_form/Create_form.jsx

Se corrigió bug en créate form.

Se corrigio bug en create form

---

Front_end/src/pages/Dashboard/clients/clients.jsx

Se volvio a integrar el button para desactivar usuario.

Se volvio a integrar el button para desactivar usuario

---

Front_end/src/pages/Dashboard/clients/clients.jsx

se corrrigio permisos de admin...

se corrigio permisos de super admin

---

Front_end/src/Components/Cards/Cards.jsx
Front_end/src/pages/Dashboard/css/products.module.css
Front_end/src/pages/Dashboard/products/products.jsx

Se agrego paginado a dashboard

Se agrego paginado a dashboard

---

Front_end/src/Components/Cart/Cart.jsx
Front_end/src/Components/Detail/Detail.jsx

solucion conflictos

---

Front_end/src/pages/Dashboard/css/HomeAdmin.module.css

se modifico testarea

---

Front_end/src/pages/Dashboard/Statistics/Statistics.jsx

Se corrrigio bug

---

Back_end/src/controllers/orderControllers.js
Front_end/src/Components/Cart/Cart.jsx
Front_end/src/Components/Detail/Detail.jsx

se incorporo alerts personalizadas

se incorporo alerts personalizadas

---

Front_end/src/Components/Card/card.jsx
Front_end/src/Components/Card/card.module.css

Se corrigió bug en frontend

---

Back_end/src/controllers/categoryControllers.js

Category bug

---

Front_end/src/Components/SearchBar/SearchBar.module.css

se corrigio altura searchbar
